from pathlib import Path
import os
import sys

Import("env")

inc = Path(env["PROJECT_INCLUDE_DIR"])
inc.mkdir(parents=True, exist_ok=True)

def v(name):
    if name in os.environ:
        return os.getenv(name)
    
    try:
        value = env.GetProjectOption(f"custom_{name.lower()}")
        if value is not None:
            return value
    except:
        pass
    
    print(f"ERROR: {name} not found in environment or platformio.ini")
    print(f"Please set {name} environment variable or custom_{name.lower()} in platformio.ini")
    sys.exit(1)

cfg = f"""#pragma once
/* AUTOGENERATED */

#define WIFI_SSID "{v("WIFI_SSID")}"
#define WIFI_PASSWORD "{v("WIFI_PASSWORD")}"
#define RELAY_GPIO {v("RELAY_GPIO")}
#define TEMP_SENSOR_GPIO {v("TEMP_SENSOR_GPIO")}
#define DEFAULT_SETPOINT {v("DEFAULT_SETPOINT")}f
"""

(inc / "config_autogen.h").write_text(cfg)